### ISSUE TITLE
Release to NPM

### ISSUE THREAD

**Issue by pelikhan** [ARMmbed/dapjs#23]
Would it be possible to push release into an NPM package? This would make it easier to take a dependency on this library in MakeCode Microbit.

**Comment by thegecko** [comment]
Hi Peli,

we are still in the process of restructuring the codebase, do you have a timeline you are working towards?

**Comment by pelikhan** [comment]
pretty much ASAP :) @jaustin

**Comment by thegecko** [comment]
Released dapjs@1.0.0
