### ISSUE TITLE
partial flashing support

### ISSUE THREAD

**Issue by mmoskal** [ARMmbed/dapjs#24]
Right now, you provide code to flash the board with a given hex file (or rather binary), but it always erases the whole flash and re-writes everything which is quite slow.

In MakeCode we have custom code that uploads checksum-computing code to the device, compares generated array of per-page checksums with what's expected and flashes the pages that need that, see https://github.com/Microsoft/pxt-microbit/blob/master/editor/extension.ts

There is some "analyzer" code in DapJS, but it's not used. It also seems to use CRC32, which without hardware support is quite sluggish on slow MCUs like the nrf51. Murmur3 is much faster. The source for the binary murmur3 blob is here: https://github.com/Microsoft/pxt-microbit/tree/master/external/sha (I used that to compare perf of different hashing functions on the microbit)

This seems like a fairly typical thing that one wants to do when flashing a device, and thus I believe it belongs in DapJS. This way the interface area between DapJS and MakeCode would drastically shrink.

**Comment by thegecko** [comment]
Hi @mmoskal,

We acknowledge that firmware flashing can be undertaken through the debug interface, however this isn't a scenario we intend to support for production in DAPjs. The latest DAPLink firmware exposes the ability to flash firmware utilising the mass storage device code which also guarantees to the device is recoverable after a bad flash.

For partial flashing support, I think the best place to implement this would be in the DAPLink firmware, we can then expose this via DAPjs.

thoughts?

**Comment by mmoskal** [comment]
Sure, if DAPLink does quick flashing for hex files that would be a win for everyone. I'm not sure how fast can you stream data over the control pipe, but HID channel is limited to 64k/s, which means that flashing a typical file on microbit will take at least around 10 seconds. It might be faster over the control pipe, but it seemed quite slow in your online demo.

For now, I have just hacked our existing version of dapjs to use control transfers and it seems to work.

Thank you!
