### ISSUE TITLE
Windows OS supported?

### ISSUE THREAD

**Issue by caizelin** [ARMmbed/dapjs#31]
@thegecko Hi Rob,
It works well on macOS. But on Windows OS(win10 I have tested), it seems that there is not driver for the `WebUSB: CMSIS-DAP` device. Is it the libusb driver issue?  

Thanks & Best Rds
Zelin

**Comment by thegecko** [comment]
Using which transport?
Using node or web?

**Comment by caizelin** [comment]
I am using web on Chrome. I will try node later.

**Comment by caizelin** [comment]
@thegecko I just solved the problem. It needs to enable the new experimental USB backend for Windows on the page `chrome://flags/` in Chrome.

**Comment by arekzaluski** [comment]
@caizelin Please check you Chrome version. From version 65 no flags should be required, default settings should be sufficient.
Also be aware that this example is using interface 0xFF and control transfer to flash program on a board.

**Comment by caizelin** [comment]
@arekzaluski My Chrome version is  67.0.3396.99(64bit). Yes, I am using this example to program a board with the latest DAPLink firmware. It works fine on macOS.

**Comment by thegecko** [comment]
@caizelin Have you ever installed the Mbed serial driver? It shouldn't be used on Windows 10 and can cause this issue.

**Comment by arekzaluski** [comment]
@caizelin Did it work for you? Remember also to disable experimental USB backend in `chrome://flags/`

**Comment by arekzaluski** [comment]
By Latest DAPLink did you mean the latest released version or latest master? Could you also tell me what board are you using? I'll try to reproduce it.

**Comment by caizelin** [comment]
@arekzaluski I am using the latest master(with version 0246) and a lpc11u35 dipdap sdt board.

**Comment by thegecko** [comment]
I'm not aware of any issue using this on Windows as long as you follow requirements for WebUSB:

- You use Chrome version 61 or newer
- You serve your page over https://

Please reopen this issue if any further data can be presented.
