### ISSUE TITLE
Is this only for STM32F1 DAPLink

### ISSUE THREAD

**Issue by tekbee** [ARMmbed/dapjs#32]
Hi, I am making a new board which has a DAP on and I want to make sure it compatible with WebUSB and the latest DAPLink - which chip is most compatible as of today with these libraries and webusb - STM32F103, LPC11U35 OR KL25/26Z?

**Comment by thegecko** [comment]
@tekbee The library should work with all [Mbed enabled boards](https://os.mbed.com/platforms/?mbed-enabled=15) which have the CMSIS-DAP chip on them.

Note that the latest DAPLink containing WebUSB support needs to be built from the [DAPLink source](https://github.com/ARMmbed/DAPLink) until we have prepared a new firmware release on https://armmbed.github.io/DAPLink/.

As the CMSIS-DAP chip is separate form the chip being debugged, it shouldn't make a difference which of those chips you choose. However, I haven't tested any of them yet.

I'll add a list to the README of tested boards.
