### ISSUE TITLE
DAPjs robust SWD signals

### ISSUE THREAD

**Issue by wjzhang** [ARMmbed/dapjs#37]
Hi:
   when I use DAPjs  read memory data, almost always get "Error: Transfer response FAULT" in dapjs\lib\proxy\cmsis-dap.js:297:23 .
   
   the openocd and pyocd use same config/connection are ok. no problem. 
   the DAPjs seem need more robust SWD signals.
   do the DAPjs has retry strategy when SWD operating failed? 
   target / SWD debugger conection:
![img_20190201_124721](https://user-images.githubusercontent.com/9528181/52103437-9a3cde00-2620-11e9-9ecc-4558cf777b2a.jpg)
![img_20190201_124812](https://user-images.githubusercontent.com/9528181/52103442-9f019200-2620-11e9-837d-373f36eb2a96.jpg)

**Comment by wjzhang** [comment]
I also modify the SWD clock. like this
const processor = new DAPjs.CortexM(transport, 0, 500000);
still some read will be failed.

**Comment by arekzaluski** [comment]
Hi @wjzhang thank you for reporting an issue. Any reason why have you closed it?
Can you let us know the exact setup you are using? Only then we will be able to reproduce it.

Please let us know:
1) Board used
2) DAPLink version
3) DAPjs version

**Comment by wjzhang** [comment]
Hi Arek:
      sorry for my mistake.
      i use DAPjs access a memory address did not exist, it caused
Error("Transfer
response FAULT").

   Have a nice day!
Best regards!
Zhangwenjin

**Comment by arekzaluski** [comment]
No worries, do not hesitate to open a ticket if you find any issue.
