### ISSUE TITLE
the DAPjs ADI readBlock()/writeBlock() mismatch Uint32Array type.  and readBlock did not  return correct Word size.

### ISSUE THREAD

**Issue by wjzhang** [ARMmbed/dapjs#45]
when i try execute some code in target RAM, found the  "Incorrect bytecount written" when the Code size is large than 64 bytes.  it caused by the readBlock()/writeBlock() treat Uint32Array  as Uint8Array.

**Comment by wjzhang** [comment]
change in ADI.ts:  

  /**
     * Read a block of 32-bit words from a memory access port register
     * @param register ID of register to read from
     * @param count The count of values to read
     * @returns Promise of register data
     */
    public readBlock(register: number, count: number): Promise<Uint32Array> {
        let chain: Promise<Uint32Array[]> = this.transferSequence([
            this.writeAPCommand(APRegister.CSW, CSWMask.VALUE | CSWMask.SIZE_32),
            this.writeAPCommand(APRegister.TAR, register),
        ])
        .then(() => []);

        // Split into requests no longer than block size
        let remainder = count;
        while (remainder > 0) {
            const chunkSize = Math.min(remainder, Math.floor(this.proxy.blockSize / 4));
            chain = chain.then(results => this.proxy.transferBlock(DAPPort.ACCESS, APRegister.DRW, chunkSize)
            .then(result => [...results, result]));
            remainder -= chunkSize;
        }

        return chain
        .then(arrays => this.concatTypedArray(arrays));
    }

    /**
     * Write a block of 32-bit words to a memory access port register
     * @param register ID of register to write to
     * @param values The values to write
     * @returns Promise
     */
    public writeBlock(register: number, values: Uint32Array): Promise<void> {
        let chain: Promise<void> = this.transferSequence([
            this.writeAPCommand(APRegister.CSW, CSWMask.VALUE | CSWMask.SIZE_32),
            this.writeAPCommand(APRegister.TAR, register),
        ])
        .then(() => undefined);

        // Split values into chunks no longer than block size
        let index = 0;
        while (index < values.length) {
            const chunk = values.slice(index, index + Math.floor(this.proxy.blockSize / 4));
            chain = chain.then(() => this.proxy.transferBlock(DAPPort.ACCESS, APRegister.DRW, chunk));
            index += Math.floor(this.proxy.blockSize / 4);
        }

        return chain;
    }

for return right words size, change in cmsis-dap.ts transferBlock():

            if (typeof countOrValues === "number") {
                return new Uint32Array(result.buffer.slice(4, 4 + operationCount * 4));
            }

**Comment by wjzhang** [comment]
PR is used Issue #43

**Comment by thegecko** [comment]
Fixed with #67
