### ISSUE TITLE
Serial port reading and writing issues (WebUSB)

### ISSUE THREAD

**Issue by yarsanich** [ARMmbed/dapjs#50]
Hi.

I am working with serial reading and writing and what I found that after the `serialWrite` buffer that was passed to `serialWrite` as data appears in `webUSB.read` and there is no synchronization for preventing it and as a result, `EVENT_SERIAL_DATA` produce the corrupted message.

Is it possible to synchronize read and write methods in the Transport class maybe or it should be done on the client side?

In WebUSB specification I can see in and out endpoints for `controlTransferIn` and following the doc I can select that endpoint for in-stream only, but with microbit, I got `Network error: Unable to claim interface`(Changed DEFAULT_CLASS in webusb.ts).

**Comment by thegecko** [comment]
I believe this was resolved in the latest release `2.1.0`, please re-open this issue if it isn't fixed.
