### ISSUE TITLE
Micro:bit cannot be flashed after attempting to flash with 1024 pageSize

### ISSUE THREAD

**Issue by geowor01** [ARMmbed/dapjs#57]
Using the micro:bit python editor (https://python.microbit.org/v/beta) to call DAPLink.flash (https://armmbed.github.io/dapjs/docs/classes/daplink.html#flash) with a `pageSize` of `1024` on a micro:bit with the following details [DETAILS-1.TXT](https://github.com/ARMmbed/dapjs/files/3421219/DETAILS-1.TXT) gives the error `RangeError: Source is too large` and does not produce any error files on the micro:bit.

Following this, attempting to flash without passing a pageSize parameter gives an error and produces the following file on the micro:bit: [ASSERT.TXT](https://github.com/ARMmbed/dapjs/files/3421231/ASSERT.TXT).
Drag & drop produces the same assert file as well as the fail file: [FAIL.TXT](https://github.com/ARMmbed/dapjs/files/3421241/FAIL.TXT).

The light on the back of the micro:bit flashes when each is attempted, but the program running (scrolling text), does not halt at any point.

Reflashing the firmware in maintenance mode restores the ability to flash the micro:bit.

**Comment by geowor01** [comment]
This occurs whenever the `Source is too large` exception is thrown by dapjs attempting to transfer more data than the packet size of the transport (webusb).

There appears to be an unspecified and unchecked limit on the size of the array written using https://armmbed.github.io/dapjs/docs/classes/cortexm.html#writeblock in the form of https://github.com/ARMmbed/dapjs/blob/7246206b6e9e6bbd8a50e882788412e591928eb3/src/transport/webusb.ts#L82 which throws an exception if the data length, which is the length of the array, is larger than the packetSize, which when called by https://github.com/ARMmbed/dapjs/blob/7246206b6e9e6bbd8a50e882788412e591928eb3/src/transport/webusb.ts#L176 is 64.

**Comment by thegecko** [comment]
I believe this is fixed in the `execute` branch, but is still a WiP
