### ISSUE TITLE
EVENT_SERIAL_DATA emits a string, could we get the raw data?

### ISSUE THREAD

**Issue by carlosperate** [ARMmbed/dapjs#60]
Listening to the EVENT_SERIAL_DATA gets the DATA as a string format.

https://github.com/ARMmbed/dapjs/blob/87f20dcddf9dd026703daed000ae77d3c1764df4/src/daplink/index.ts#L161-L168

Any chance we can get the raw data?
As MicroPython strings are UTF-8 when the data is converted into a JS string (UTF-16) we get some characters decoded incorrectly, like `£` as `Â£`.

**Comment by thegecko** [comment]
I'll look into it when I get some time. It should be trivial to create another `.ts` class which inherits from `DAPLink` or `CmsisDAP` to do what you want in the meantime, though.
