### ISSUE TITLE
Reading invalid memory address halts communication

### ISSUE THREAD

**Issue by thegecko** [ARMmbed/dapjs#64]
If a memory address is read which isn't in range, `dapjs` crashes and the target is left in a bad state.

cc @dbatyai

**Comment by dbatyai** [comment]
A general way of reproducing this issue (using K64F, considering the device already opened/connected):

```js
const invalid = await processor.readMem32(0xFFFFFFFF);
```

This will throw a `Transfer FAULT` exception, which is to be expected. However, if we instead catch the error and try to read valid address later:

```js
try {
    const invalid = await processor.readMem32(0xFFFFFFFF);
} catch (e) {}
const valid = await processor.readMem32(0x20000000);
```

The second read hangs and does not seem to resolve.
