### ISSUE TITLE
How should I generate not compressed "dap.umd.js"?

### ISSUE THREAD

**Issue by DeqingSun** [ARMmbed/dapjs#71]
I got redirected by the old project https://github.com/ARMmbed/dapjs-web-demo
My goal is to use WebUSB and have a webpage talk to hardware, and sorry I'm not a NodeJS expert.

After I downloaded this repo and run ```npm install```, the dist folder was still empty.

I did find some file in "gh-pages" branch, and they seem generated automatically and up to date. However, they are compressed. Is it possible to generate a not-compressed version for debugging in the browser?

**Comment by thegecko** [comment]
To use this library as-is, download it from [npm](https://www.npmjs.com/package/dapjs).

It includes `.map` files, so you should be able to debug it using the original source.

If for some reason you want to compiler it yourself:

- clone it: `git clone https://github.com/ARMmbed/dapjs`
- add dependencies: `npm i`
- build it: `npm run build`

If you want to remove the minification, comment it out in the [rollup config](https://github.com/ARMmbed/dapjs/blob/master/rollup.config.js#L41)

**Comment by DeqingSun** [comment]
Great! Thank you.
