### ISSUE TITLE
WebUSB serial: polling only?

### ISSUE THREAD

**Issue by ccattuto** [ARMmbed/dapjs#90]
Hello, is there any way to get blocking behavior for serial reads, or polling is the only possibility?

**Comment by thegecko** [comment]
cc @arekzaluski

**Comment by arekzaluski** [comment]
Hi @ccattuto. Polling is the only possibility at the moment to get serial data.

**Comment by ccattuto** [comment]
Thanks for the info!

**Comment by thegecko** [comment]
Glad to have answered your question, feel free to create a PR if you want to add any functionality/
