### ISSUE TITLE
single byte write to target memory?

### ISSUE THREAD

**Issue by ccattuto** [ARMmbed/dapjs#91]
Hello, sorry for the naive question. Is there a fundamental reason for not having a `writeMem8Command()` ?
What is the preferred way to execute non-word-aligned single byte memory writes on, e.g., Cortex M targets ?
Thanks!

**Comment by XGM001** [comment]
DMA write, or data is re-allocated into bytes,

**Comment by ccattuto** [comment]
Thanks, although I'm not sure I understand. pyOCD does provide single byte semantics.
